name: Keep App Awake

on:
  schedule:
    # 매 60분(1시간)마다 실행 (한국 시간 기준이 아닌 UTC 기준이지만, 간격이 중요함)
    # "0 * * * *" -> 매시 정각 (예: 1:00, 2:00, 3:00 ...)
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Streamlit App
        run: |
          curl -v https://auction1-pto-check-yoco6lndlsgq4pubmtqw3h.streamlit.app/ \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
          echo "Ping sent to keep the app awake with Browser User-Agent!"
